apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: psn-account-lookup-secrets
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: your-secret-store
  target:
    name: psn-account-lookup-secrets
    creationPolicy: Owner
  data:
    - secretKey: PSN_NPSSO
      remoteRef:
        key: psn-account-lookup-api
        property: PSN_NPSSO
